# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.26

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.26.4/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.26.4/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/andrewmiller/Dev/C/umbral

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/andrewmiller/Dev/C/umbral

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.26.4/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.26.4/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewmiller/Dev/C/umbral/CMakeFiles /Users/andrewmiller/Dev/C/umbral//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/andrewmiller/Dev/C/umbral/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named umbral-internal

# Build rule for target.
umbral-internal: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 umbral-internal
.PHONY : umbral-internal

# fast build rule for target.
umbral-internal/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/build
.PHONY : umbral-internal/fast

#=============================================================================
# Target rules for targets named umbral

# Build rule for target.
umbral: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 umbral
.PHONY : umbral

# fast build rule for target.
umbral/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral.dir/build.make CMakeFiles/umbral.dir/build
.PHONY : umbral/fast

#=============================================================================
# Target rules for targets named shaders

# Build rule for target.
shaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 shaders
.PHONY : shaders

# fast build rule for target.
shaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/shaders.dir/build.make CMakeFiles/shaders.dir/build
.PHONY : shaders/fast

src/core/internal.o: src/core/internal.cpp.o
.PHONY : src/core/internal.o

# target to build an object file
src/core/internal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/internal.cpp.o
.PHONY : src/core/internal.cpp.o

src/core/internal.i: src/core/internal.cpp.i
.PHONY : src/core/internal.i

# target to preprocess a source file
src/core/internal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/internal.cpp.i
.PHONY : src/core/internal.cpp.i

src/core/internal.s: src/core/internal.cpp.s
.PHONY : src/core/internal.s

# target to generate assembly for a file
src/core/internal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/internal.cpp.s
.PHONY : src/core/internal.cpp.s

src/core/umb_mem.o: src/core/umb_mem.cpp.o
.PHONY : src/core/umb_mem.o

# target to build an object file
src/core/umb_mem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/umb_mem.cpp.o
.PHONY : src/core/umb_mem.cpp.o

src/core/umb_mem.i: src/core/umb_mem.cpp.i
.PHONY : src/core/umb_mem.i

# target to preprocess a source file
src/core/umb_mem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/umb_mem.cpp.i
.PHONY : src/core/umb_mem.cpp.i

src/core/umb_mem.s: src/core/umb_mem.cpp.s
.PHONY : src/core/umb_mem.s

# target to generate assembly for a file
src/core/umb_mem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/core/umb_mem.cpp.s
.PHONY : src/core/umb_mem.cpp.s

src/gfx/umb_vk.o: src/gfx/umb_vk.cpp.o
.PHONY : src/gfx/umb_vk.o

# target to build an object file
src/gfx/umb_vk.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/gfx/umb_vk.cpp.o
.PHONY : src/gfx/umb_vk.cpp.o

src/gfx/umb_vk.i: src/gfx/umb_vk.cpp.i
.PHONY : src/gfx/umb_vk.i

# target to preprocess a source file
src/gfx/umb_vk.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/gfx/umb_vk.cpp.i
.PHONY : src/gfx/umb_vk.cpp.i

src/gfx/umb_vk.s: src/gfx/umb_vk.cpp.s
.PHONY : src/gfx/umb_vk.s

# target to generate assembly for a file
src/gfx/umb_vk.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/gfx/umb_vk.cpp.s
.PHONY : src/gfx/umb_vk.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral.dir/build.make CMakeFiles/umbral.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral.dir/build.make CMakeFiles/umbral.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral.dir/build.make CMakeFiles/umbral.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sys/umb_app.o: src/sys/umb_app.cpp.o
.PHONY : src/sys/umb_app.o

# target to build an object file
src/sys/umb_app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_app.cpp.o
.PHONY : src/sys/umb_app.cpp.o

src/sys/umb_app.i: src/sys/umb_app.cpp.i
.PHONY : src/sys/umb_app.i

# target to preprocess a source file
src/sys/umb_app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_app.cpp.i
.PHONY : src/sys/umb_app.cpp.i

src/sys/umb_app.s: src/sys/umb_app.cpp.s
.PHONY : src/sys/umb_app.s

# target to generate assembly for a file
src/sys/umb_app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_app.cpp.s
.PHONY : src/sys/umb_app.cpp.s

src/sys/umb_file.o: src/sys/umb_file.cpp.o
.PHONY : src/sys/umb_file.o

# target to build an object file
src/sys/umb_file.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_file.cpp.o
.PHONY : src/sys/umb_file.cpp.o

src/sys/umb_file.i: src/sys/umb_file.cpp.i
.PHONY : src/sys/umb_file.i

# target to preprocess a source file
src/sys/umb_file.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_file.cpp.i
.PHONY : src/sys/umb_file.cpp.i

src/sys/umb_file.s: src/sys/umb_file.cpp.s
.PHONY : src/sys/umb_file.s

# target to generate assembly for a file
src/sys/umb_file.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_file.cpp.s
.PHONY : src/sys/umb_file.cpp.s

src/sys/umb_window.o: src/sys/umb_window.cpp.o
.PHONY : src/sys/umb_window.o

# target to build an object file
src/sys/umb_window.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_window.cpp.o
.PHONY : src/sys/umb_window.cpp.o

src/sys/umb_window.i: src/sys/umb_window.cpp.i
.PHONY : src/sys/umb_window.i

# target to preprocess a source file
src/sys/umb_window.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_window.cpp.i
.PHONY : src/sys/umb_window.cpp.i

src/sys/umb_window.s: src/sys/umb_window.cpp.s
.PHONY : src/sys/umb_window.s

# target to generate assembly for a file
src/sys/umb_window.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/umbral-internal.dir/build.make CMakeFiles/umbral-internal.dir/src/sys/umb_window.cpp.s
.PHONY : src/sys/umb_window.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... shaders"
	@echo "... umbral"
	@echo "... umbral-internal"
	@echo "... src/core/internal.o"
	@echo "... src/core/internal.i"
	@echo "... src/core/internal.s"
	@echo "... src/core/umb_mem.o"
	@echo "... src/core/umb_mem.i"
	@echo "... src/core/umb_mem.s"
	@echo "... src/gfx/umb_vk.o"
	@echo "... src/gfx/umb_vk.i"
	@echo "... src/gfx/umb_vk.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sys/umb_app.o"
	@echo "... src/sys/umb_app.i"
	@echo "... src/sys/umb_app.s"
	@echo "... src/sys/umb_file.o"
	@echo "... src/sys/umb_file.i"
	@echo "... src/sys/umb_file.s"
	@echo "... src/sys/umb_window.o"
	@echo "... src/sys/umb_window.i"
	@echo "... src/sys/umb_window.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

